// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/community" | "/dashboard/findings" | "/dashboard/findings/[id]" | "/dashboard/findings/map" | "/dashboard/findings/new" | "/dashboard/image-gallery" | "/dashboard/images" | "/dashboard/tags" | "/dashboard/tags/categories" | "/login" | "/signup"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/community/findings" | "/api/findings" | "/api/findings/[id]" | "/api/findings/stats" | "/api/geo/admin-units" | "/api/images" | "/api/images/[id]" | "/api/images/bulk" | "/api/notifications" | "/api/notifications/read-all" | "/api/tag-categories" | "/api/tag-categories/[id]" | "/api/tags" | "/api/tags/[id]" | "/api/user-images"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/community/findings": {}
  "/api/findings": {}
  "/api/findings/[id]": { "id": string; }
  "/api/findings/stats": {}
  "/api/geo/admin-units": {}
  "/api/images": {}
  "/api/images/[id]": { "id": string; }
  "/api/images/bulk": {}
  "/api/notifications": {}
  "/api/notifications/read-all": {}
  "/api/tag-categories": {}
  "/api/tag-categories/[id]": { "id": string; }
  "/api/tags": {}
  "/api/tags/[id]": { "id": string; }
  "/api/user-images": {}
  "/dashboard": {}
  "/dashboard/community": {}
  "/dashboard/findings": {}
  "/dashboard/findings/[id]": { "id": string; }
  "/dashboard/findings/map": {}
  "/dashboard/findings/new": {}
  "/dashboard/image-gallery": {}
  "/dashboard/images": {}
  "/dashboard/tags": {}
  "/dashboard/tags/categories": {}
  "/login": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
