/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/api/mobile/sessions/route`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSessions`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SessionCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/session/new` | `/session/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/session/[id]` | `/session/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/findings` | `/findings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app/api/mobile/sessions/route`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useSessions`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SessionCard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/session/new` | `/session/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/session/[id]` | `/session/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/findings` | `/findings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/sessions` | `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../../web/app/api/mobile/sessions/route${`?${string}` | `#${string}` | ''}` | `/../hooks/useSessions${`?${string}` | `#${string}` | ''}` | `/../components/SessionCard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/session/new${`?${string}` | `#${string}` | ''}` | `/session/new${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/session/[id]${`?${string}` | `#${string}` | ''}` | `/session/[id]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/findings${`?${string}` | `#${string}` | ''}` | `/findings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/sessions${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/api/mobile/sessions/route`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useSessions`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SessionCard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/session/new` | `/session/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/session/[id]` | `/session/[id]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/findings` | `/findings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
